### PR TITLE
ExistsAsync(object poco)

### PR DESCRIPTION
**Pull request by coderasm**
I am working on a small project and am using generics in such a way, I would like to test for the existence of a record through a poco and not through a key directly. A portion of my implementation below, shows what I am needing. I went ahead and implemented the `Task<bool> ExistsAsync(object poco)` into asyncpoco. Have a look at this merge request and decide if you want to incorporate it. Petapoco horribly violates the DRY principle. I may take it upon myself to refactor portions of the code to get rid of all the duplication.
```C#
public async Task<bool> Exists(T poco) {
     return await database.ExistsAsync(poco)
}
```
It takes into account autoincrementing pocos. I created a customized exception to warn about autoincrement pocos not possibly existing. I also included tests for the new behavior in PetaTest and they are passing.

### CODE REVIEW

**Comment by coderasm** [comment]
Even though the tests were passing, when I try to use this in production, It acts as if it is never executed.

**Comment by coderasm** [comment]
It looks like I got it working I had a misplaced end region marker in Database.cs and also rebuilt the plugin under release instead of debug.

**Comment by coderasm** [comment]
I'm making a new pull request.

**Comment by tmenier** [comment]
Ok. I should be able to review it soon, just so you don't think I'm ignoring.

**Pull request closed without merging**
