### PR TITLE
Add support for custom insert- and update templates.

### PR DESCRIPTION
**Pull request by khellang**
To support PostgreSQL JSON and JSONB columns.

Is there a better way to solve this?

See https://github.com/CollaboratingPlatypus/PetaPoco/commit/dee123251f8225cdd13ea2fe7f1e2659721b3785.

### CODE REVIEW

**Comment by tmenier** [comment]
Thanks for this. In just a couple days I'm planning on doing the official 2.0 release, so I'll plan on reviewing this and making a decision on it soon after. At a glance, I understand the problem it solves and I do think this approach gives you the ultimate flexibility. But given how popular the JSON features of PostgreSQL, I'm also not opposed to solving this in a more direct, "baked-in" way. I'm not even sure what that means exactly to be honest, I'd just like to take a little time to evaluate options.

**Comment by khellang** [comment]
> But given how popular the JSON features of PostgreSQL, I'm also not opposed to solving this in a more direct, "baked-in" way.

100% agreed. The reason I pushed this is because it's the only thing keeping us from migrating from PetaPoco. Maybe it makes sense to do something first-class for Postgres JSON in addition? Like you said, this is a nice escape hatch for scenarios like this.

**Comment by tmenier** [comment]
And compatibility with PetaPoco is always a "pro", although it's not the most important factor.

**Comment by khellang** [comment]
Hey @tmenier! Have you had time to look at this. We're looking to migrate away from PetaPoco and this is the only thing holding us back. Right now, we're looking at just maintaining our own fork of AsyncPoco to unblock ourselves.

**Comment by tmenier** [comment]
Thanks for the reminder. Could you provide a test (or tests) for using this with PostgreSQL/JSON? Tests are great not just to prove a feature works but to demonstrate how to use it, which isn't abundantly clear to me from looking at the code.

**Comment by tmenier** [comment]
Any progress on this?

**Comment by khellang** [comment]
We unblocked ourselves by building our own fork. I don't have much time to finish this after all this time, sorry.

**Pull request closed without merging**
